### PR TITLE
Support rails 7.2 and update gemfiles

### PR DESCRIPTION
**Pull request by npezza93**

### CODE REVIEW

**Comment by npezza93** [comment]
Fixes #178

**Comment by andersonkrs** [comment]
Could anyone review this? It is blocking updating to the latest Rails. I've tested @npezza93 branch for couple for weeks in production and seems stable 😄

**Comment by arni1981** [comment]
Seems stable to me also, been using it for a couple of weeks as well.

**Comment by fractaledmind** [comment]
Also works for me

**Pull request merged**
